baseURL: /
title: Zach Gagnon
theme: hugo-theme-m10c
image: "config_files/profile.jpg"
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About Me
      url: /about/
      weight: 2
params:
  author: Zach Gagnon
  description: This is a website I made about myself and my work in my statistical computing class.
  avatar: "/static/IMG_2110.PNG"
  menu_item_separator: ' - '
