baseURL: /
title: Zach Gagnon![](/./config_files/profile.jpg)
theme: hugo-theme-m10c
paginate: 8
menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: about
      name: About Me
      url: /about/
      weight: 2
params:
  author: Zach Gagnon
  description: This is a website I made about myself and my work in my statistical computing class.
  menu_item_separator: ' - '
